// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOF2k7f80UnxeYc3jNahpzgDdRtjO5Boc',
    appId: '1:162019010208:web:444a567855da9e70e50bc5',
    messagingSenderId: '162019010208',
    projectId: 'wings-mobile-2b8bb',
    authDomain: 'wings-mobile-2b8bb.firebaseapp.com',
    storageBucket: 'wings-mobile-2b8bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClPni9hEiVot-1Ayweo4AAkoR9fpIx_pw',
    appId: '1:162019010208:android:d879a16059dc2a39e50bc5',
    messagingSenderId: '162019010208',
    projectId: 'wings-mobile-2b8bb',
    storageBucket: 'wings-mobile-2b8bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByyWpkZPfYaoxI_08h-eImH6dhPdUuF-c',
    appId: '1:162019010208:ios:0e6088cd51024453e50bc5',
    messagingSenderId: '162019010208',
    projectId: 'wings-mobile-2b8bb',
    storageBucket: 'wings-mobile-2b8bb.appspot.com',
    iosClientId: '162019010208-k0cnbkkmresohc3kidrmcvpnb632kfqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.wingsMobile',
  );
}
